### ISSUE TITLE
App crashes after file has been sent

### ISSUE THREAD

**Issue by ShortDevelopment** [ShortDevelopment/Nearby-Sharing-Windows#1]
#### Output
```
[System.err] java.lang.NoSuchMethodError: no non-static method "Lcom/microsoft/connecteddevices/remotesystems/commanding/nearshare/NearShareSenderEnumAsyncOperation;.complete(ILjava/lang/String;)V"
[libc++abi] terminating with uncaught exception of type ConnectedDevices::WrappedPlatformSpecificException
```

**Comment by ShortDevelopment** [comment]
This issue is also tracked here: https://github.com/microsoft/project-rome/issues/85

**Comment by ShortDevelopment** [comment]
I just patched the library with [Recaf](https://www.coley.software/Recaf/).
<details>
<summary>Java bytecode</summary>

```
DEFINE FINAL complete(I intValue, Ljava/lang/String; strValue)V
START:
ALOAD this
ILOAD intValue
invokespecial com/microsoft/connecteddevices/remotesystems/commanding/nearshare/NearShareSenderEnumAsyncOperation.complete(I)V
RETURN
END:
```

</details>

**Comment by mediaexplorer74** [comment]
> I just patched the library with [Recaf](https://www.coley.software/Recaf/).
> 
> Java bytecode

Wow, you used a bytecode editor (Recaf).... Hacker level! I thinked that you used Android Studio for Java code debugging, etc...
