### ISSUE TITLE
Add support for udp advertisement

### ISSUE THREAD

**Issue by BlockyTheDev** [ShortDevelopment/Nearby-Sharing-Windows#31]
My setup: 
- Android device (Android 10) connected through USB-C network adaptor to home network
- Desktop PC without WLAN/Bluetooth (Windows 11) connected trough LAN cable to home network

It's already possible to send files from the Android device to the Windows system because the PC in the home network is shown in the device overview after pressing "Send" and selecting the file in the app. My problem is that it's not possible to receive files on Android with the same setup, because Windows doesn't showe the Android device.

If this can be implemented it would be great to see this feature in the future.

**Comment by ShortDevelopment** [comment]
This is actually an interesting edge case!
The CDP protocol is laid out to do discovery over BluetoothLE Beacons to guarantee the devices are actually “nearby” and later switch to local network if possible (TransportUpgrade).

But there’s actually a discovery method that works via network only (no Bluetooth needed).
This one is used when you’re sending data to your PC.

Interestingly, it does not work with all PCs anymore (See #17)...

As I started working on my own implementation, I tried to do discovery via this network method, but Windows did not seem to respond, so it might actually be impossible to get this working, but it needs further investigation…

@BlockyTheDev  Could you privately send me the following information via mail ([nearshare@shortdev.de](mailto:nearshare@shortdev.de))?
 - Content of `%LocalAppData%\ConnectedDevicesPlatform\CDPGlobalSettings.cdp`
 - Windows Specification (Win+R `ms-settings:about`)

**Comment by BlockyTheDev** [comment]
> This is actually an interesting edge case! The CDP protocol is laid out to do discovery over BluetoothLE Beacons to guarantee the devices are actually “nearby” and later switch to local network if possible (TransportUpgrade).
> 
> But there’s actually a discovery method that works via network only (no Bluetooth needed). This one is used when you’re sending data to your PC.
> 
> Interestingly, it does not work with all PCs anymore (See #17)...
> 
> As I started working on my own implementation, I tried to do discovery via this network method, but Windows did not seem to respond, so it might actually be impossible to get this working, but it needs further investigation…
> 
> @BlockyTheDev Could you privately send me the following information via mail ([nearshare@shortdev.de](mailto:nearshare@shortdev.de))?
> 
> * Content of `%LocalAppData%\ConnectedDevicesPlatform\CDPGlobalSettings.cdp`
> * Windows Specification (Win+R `ms-settings:about`)

I have sent the information.

**Comment by ShortDevelopment** [comment]
Great, thanks!
I'll have a look!

**Comment by ShortDevelopment** [comment]
@BlockyTheDev 
This could now work in theory but Windows does not seem to advertise itself via udp.
But I could maybe create a patch for that...

**Comment by BlockyTheDev** [comment]
> But I could maybe create a patch for that...

Would be nice...
