### ISSUE TITLE
Share files between two Android devices

### ISSUE THREAD

**Issue by sergd88** [ShortDevelopment/Nearby-Sharing-Windows#37]
This will be a whole cycle of suggestions (at least those that I still remember, because I have already forgotten some of them, so the list may be added over time), some of them are obvious and may have already been planned, and some are more likely not. I don't know your vision for the further development of the application in terms of small functionality, but I will write what I lack in such applications and what I would like to see here. And I wish you further development and creative effort.

Add the ability to share files between Android <=> Android devices. This will allow you to have a universal tool for exchanging files between Windows and Android devices in any combination, without the need to use any additional application for this. Well, of course, this will allow you to expand and reach a much larger audience of users.

**Comment by ShortDevelopment** [comment]
I've already tested that but for some reason (I don't know yet), the android `cdp` implementation does not want some of the messages my custom receive implementation is sending.

**Comment by ShortDevelopment** [comment]
It seems like the ms android implementation of `cdp` is extremly pedantic about `CommonHeader.RequestId` and `BinaryMsgHeader.MessageId`.

**Comment by sergd88** [comment]
Sadly 😞

**Comment by ShortDevelopment** [comment]
Fixed in [`custom-send-impl`](https://github.com/ShortDevelopment/Nearby-Sharing-Windows/tree/custom-send-impl)
