### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by sergd88** [ShortDevelopment/Nearby-Sharing-Windows#38]
Add a dark theme to the app.

**Comment by ShortDevelopment** [comment]
Actually, the app already responds to the system theme settings though there are still some unpleasant parts.

@sergd88 Do you suggest a toggle in the settings?

**Comment by ShortDevelopment** [comment]
- [ ] Fix buttons
 - [ ] Fix send UI
 - [ ] Toggle in settings

**Comment by sergd88** [comment]
> Actually, the app already responds to the system theme settings though there are still some unpleasant parts.
> 
> @sergd88 Do you suggest a toggle in the settings?

The switch in the settings, in my opinion, looks quite logical, considering that the system setting of the theme does not work for everyone. Well, it will also add more flexibility to users who like to combine light and dark themes.
