### ISSUE TITLE
Duplicate device

### ISSUE THREAD

**Issue by obrobrio2000** [ShortDevelopment/Nearby-Sharing-Windows#4]
When choosing the recipient device, the same device is shown twice. The device is the same and the transfer works with whichever you choose. In this screenshot, the laptop "Android001" is shown once but the laptop "C940" is shown twice.
Android device: Samsung Galaxy Note20 Ultra
Windows device: Lenovo Yoga C940-14
![Screenshot_20220426-185057_Nearby Sharing (Windows)](https://user-images.githubusercontent.com/62136803/165352911-63b523ff-249c-40f4-af47-a8afccf6ee15.jpg)

**Comment by ShortDevelopment** [comment]
Thanks for reporting this issue!
I'm going to look at it in about a week once I got more time...

**Comment by ShortDevelopment** [comment]
It does not seem to be a bug, but rather to options.
For one entry in the list `DEVICE.Apps.FirstOrDefault()?.IsAvailableBySpatialProximity` evaluates to `true` (`false` for the second device).
The one with `IsAvailableBySpatialProximity == false` seems to transfer data faster.
The [documentation](https://docs.microsoft.com/en-us/java/api/com.microsoft.connecteddevices.remotesystems.remotesystemapp.getisavailablebyspatialproximity?view=rome-android-latest) does not really explain, what this means.

**Comment by obrobrio2000** [comment]
> It does not seem to be a bug, but rather to options. For one entry in the list `DEVICE.Apps.FirstOrDefault()?.IsAvailableBySpatialProximity` evaluates to `true` (Spatial) (`false` for the second device (Fast)). The one with `IsAvailableBySpatialProximity == false` seems to transfer data faster. The [documentation](https://docs.microsoft.com/en-us/java/api/com.microsoft.connecteddevices.remotesystems.remotesystemapp.getisavailablebyspatialproximity?view=rome-android-latest) does not really explain, what this means.
> 
> "Fast" is only available if WiFi is turned on. "Spatial" is only available if Bluetooth is turned on.

Thank you for looking at it!
It would be more convenient to only display the fastest choice available, so if Fast and Spatial are both available only display the Fast one.

**Comment by ShortDevelopment** [comment]
That would make sense, but keep in mind that I only did a quick tes” with my phone and laptop; This is by no means representative.
This could also potentially lead to hiding one of two devices that have the same name (For the “fast” option I only get the device name as the id; for the “special” option I get the bluetooth id)
I try to soon push and update to the store that displays which option is which, so it can be tested by more people on more devices…

**Comment by ShortDevelopment** [comment]
@obrobrio2000 As I recently had more time, I just released a new version to the store with some general improvements and also the indication mentioned above.
It would be great if you could quickly test the speed of both options once the update has been reviewed.
If my tests are replicable with other devices, I'd try to come up with a good way to possibly only show the faster option (if that turns out to be useful).

**Comment by obrobrio2000** [comment]
> @obrobrio2000 As I recently had more time, I just released a new version to the store with some general improvements and also the indication mentioned above. It would be great if you could quickly test the speed of both options once the update has been reviewed. If my tests are replicable with other devices, I'd try to come up with a good way to possibly only show the faster option (if that turns out to be useful).

Hi, sorry if I just answer now but I've been very busy. I tried with two laptops but same result: it only shows me the Fast option (and it works perfectly). When I try to disable wifi on these PCs (keeping bluetooth active) and try to send some files it doesn't give me any Slow option. It doesn't give me anything. In short, it only sees devices if they have wifi enabled (and therefore they are Fast).

**Comment by ShortDevelopment** [comment]
Great, thanks for testing!
