### ISSUE TITLE
A separate app preview version for Google Play

### ISSUE THREAD

**Issue by sergd88** [ShortDevelopment/Nearby-Sharing-Windows#52]
In my opinion, it would be more logical to get the preview version of the application separately in Google Play (for example, as it is implemented in most browsers), so that you can use it with the stable version of the application at the simultaneously, and not replace them with each other, as it is implemented now. This will allow, in an urgent need, if something suddenly breaks, to transfer files through a stable version of the application, and not to use another application for this. Also, it will make it possible to track changes much better and make comparisons in the work, comparing with the stable version of the program.

**Comment by ShortDevelopment** [comment]
I'm closing this for now, because I don't have the resources to manage two separat app versions.
In case something suddenly breaks, you could go back the stable track in Google Play or use the apks provided via the GitHub Releases...
