### ISSUE TITLE
Allow receiving data from PC

### ISSUE THREAD

**Issue by ShortDevelopment** [ShortDevelopment/Nearby-Sharing-Windows#8]
Custom implementation of the `cdp` protocol (transport layer).

 - [x] #11
 - [x] Listen via rfcomm (1b694db9df0fec43b8c62fd78587f0fe9478bb37)
 - [x] Connect (public keys)
 - [x] #12
 - [x] #13
 - [x] Auth (device / user certificat)
 - [x] Device Info
 - [x] CdpChannel
 - [x] #18

Custom implementation of `NearShare` protocol (application layer)
 - [x] ~#15~
 - [x] [Bond](https://github.com/microsoft/bond) schema (ValueSet)
 - [x] #14
 - [x] Uri Message
 - [x] File Transfer (single file)
 - [x] Transfer whole file
 - [x] File transfer acknowledge

UI / UX / Android 
 - [x] BT mac address settings (7cd910979ab8e9969f36d4b44301860689d77eca)
 - [x] Acceptance
 - [x] Save file

**Comment by ShortDevelopment** [comment]
https://winprotocoldoc.blob.core.windows.net/productionwindowsarchives/MS-CDP/%5BMS-CDP%5D.pdf

**Comment by fm-sys** [comment]
Just wanna say thank you! Amazing piece of software... Looking forward to the receive functionality :)

**Comment by jethoujun** [comment]
For the receive functionality, do you have a schedule?

**Comment by ShortDevelopment** [comment]
@jethoujun Sadly no.

There are several reasons:
-	I’m doing this in my free time
-	The documentation is not really complete
-	I completely have to reverse engeneer the NearShare protocol sitting on to of the (genericly documented) cdp protocol (not so difficult but…) 
-	Alongside the bond serialization schema used for NearShare (komplex)

Therefore, I can neither really estimate how much time I’m gone have nor how much work remains.

That said, I'll try to publish an early alpha version this month (no promises).

**Comment by vonDubenshire** [comment]
> That said, I'll try to publish an early alpha version this month (Nov 2022) (no promises).

I can't believe you even have the possibility of getting this to work! I thought it was impossible to send data from Windows back to Android like that.
 
@ShortDevelopment I hope you know anyone in the Windows or Google dev teams working on the full implementation that was announced last January.

> "**Do more with Android and Windows PCs.**
For the first time with Android, we’re also focused on building for other platforms, like Windows, whether it's in gaming, productivity or other areas. For example, by connecting your Android phone to your Windows PC with Fast Pair, you’ll be able to quickly set up Bluetooth accessories, sync text messages and share files with Nearby Share. We’re working with Acer, HP and Intel to bring these experiences to select Windows PCs first later this year."
https://blog.google/products/android/ces2022-bettertogether/#:~:text=Do%20more%20with,later%20this%20year.

[**Microsoft doubles down on its Android + Windows efforts in latest reorg**](https://www.windowscentral.com/microsoft-doubles-down-its-android-and-windows-efforts-latest-reorg) 
_last updated April 01, 2022
A new 'Microsoft Android' division houses Duo, SwiftKey, Launcher, and more._

> "Nearby Share is the other bigger feature shared between Android and Chrome OS. It will come to Windows PCs from Acer and HP, along with Fast Pair for Bluetooth, this year. Google is actively seeking to do reverse of Microsoft by offering more cross-service integrations to Windows, like Android games on desktop."
https://9to5google.com/2022/04/01/microsoft-android/#:~:text=Nearby%20Share%20is,on%20desktop.

> **Google is bringing Nearby Share and Fast Pair to Windows PCs**
https://9to5google.com/2022/01/05/google-nearby-share-android-windows/

![nearby_share_windows](https://user-images.githubusercontent.com/40748193/201539909-0b0be539-4013-4aff-baba-d78795565489.gif)

**Comment by ShortDevelopment** [comment]
@vonDubenshire 
Nope, I’m just doing this on my own and I sadly don’t have any contacts to any (related) Microsoft / Google staff…

**Comment by tiborbaksa** [comment]
@vonDubenshire Note that both Microsoft and Google calls their own wireless data sharing protocol Nearby Share (see [Google](https://developers.google.com/nearby), [Microsoft](https://learn.microsoft.com/en-us/windows/project-rome/nearby-sharing/)), but these are two different and incompatible protocols, just like AirDrop is. Google engineers are working to bring their protocol to Windows (see [google/nearby](https://github.com/google/nearby)). I'm not sure if Microsoft wants to bring Google's protocol to Windows or their protocol to Android, but in either case I wouldn't count on them until they announce it officially.

**Comment by jethoujun** [comment]
I think Microsoft has a BIG advantage to bring a general protocol for cross-platform file sharing, but they are not working on it with great efforts. Hope new updates from MS!

**Comment by ShortDevelopment** [comment]
It actually seems like microsoft is still actively working on nearby sharing as they’ve recently released a new protocol version (actually only minor changes).   
https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-cdp/f5a15c56-ac3a-48f9-8c51-07b2eadbe9b4   
   
They don’t seem to work on their public library any more though...

**Comment by ShortDevelopment** [comment]
@jethoujun

I know it took some time, but I’m happy to announce that a first alpha version is available right now.
Join the “Beta”-Program on google play: https://nearshare.shortdev.de/#receive-data

This version should be capable of receiving urls and (very) small files (one at a time).
It would be great if you all could grab this version and test it a little bit.

Feedback: https://forms.office.com/r/j2Fp5biXKB

As I’m doing this on my own with little to no time (right now) it might still take some time to get a (somewhat) stable release…

**Comment by fm-sys** [comment]
I'm getting a crash when trying to start the beta app:

```
[ERROR] FATAL UNHANDLED EXCEPTION: System.PlatformNotSupportedException: Arg_PlatformNotSupported
at System.Text.ASCIIUtility.GetIndexOfFirstNonAsciiByte_Intrinsified(Byte* , UIntPtr )
at System.Text.Unicode.Utf8Utility.GetPointerToFirstInvalidByte(Byte* , Int32 , Int32& , Int32& )
at System.Text.UTF8Encoding.GetCharCount(Byte* , Int32 )
at System.String.CreateStringFromEncoding(Byte* , Int32 , Encoding )
at System.Text.Encoding.GetString(Byte* , Int32 )
at System.String.CreateStringForSByteConstructor(Byte* , Int32 )
at System.String.Ctor(SByte* value)
at System.Runtime.InteropServices.Marshal.PtrToStringAnsi(IntPtr )
at Java.Interop.TypeManager.GetClassName(IntPtr )
at Android.Runtime.JNIEnv.RegisterJniNatives(IntPtr , Int32 , IntPtr , IntPtr , Int32 )

**Comment by ShortDevelopment** [comment]
@fm-sys

Are you on v1.2.1-alpha (newest beta in store)? 
What device with what OS version did you test on?

**Comment by fm-sys** [comment]
Ah, thanks for the hint. I was still on v1.2.0-alpha

**Comment by ShortDevelopment** [comment]
But good to know!! 

I did not have the time to check why the app crashed on newer android versions.
It seems to be a known bug with AOT compilation...

**Comment by ShortDevelopment** [comment]
Here's an early Christmas present! 🎄
A new, improved version is currently rolling out in the public test track on Google Play! 🎉

**Changelog**
 - Transfer acknowledgement (windows side)
 - Large transfers keep alive
 - Fast transfer while in same network (Tcp)

**Don’t forget to give feedback!**
 - _New_ Issue
 - Forms: https://forms.office.com/r/j2Fp5biXKB

**Comment by ShortDevelopment** [comment]
This supposedly „simple“ feature turned out to be a huge effort!
But now that a general receiving functionality is working, we’re finished here!

#### What happens next
 - This stuff will stay in the testing track in Play Store for a little longer until I can ensure that it has proven to be mostly stable and secure.
 - Replace the microsoft library used for sending with custom implementation
 - New platforms!
 - Please open new issues for further bugs / requests!

Don’t forget to join the brand new [Discord Server](https://discord.gg/ArFA3Nymr2)!
