### ISSUE TITLE
Please make Wiki about your cool project / solution

### ISSUE THREAD

**Issue by mediaexplorer74** [ShortDevelopment/Nearby-Sharing-Windows#9]
Hi!

"Nearby Sharing (Android-Windows)" is very cool theme. Thank you very much! Please don't leave this "project". =)
Please make Wiki about your cool project / solution (cases: Android phone - Windows PC; Android phone - Win10Mobile phone, etc. )

Also give some tech. doc links, video presentations of Project Rome, etc.
Did you know some analogues of your project?

Best / Cheers,
mediaexplorer,   "multimouse" ideologist ;)

P.S. My 2 cents:
https://github.com/mediaexplorer74/ProjectRome My Alt.ProjectRome (draft/early bird; Win32 + XF))
https://github.com/mediaexplorer74/MSGraph My MSGraph experimentation
+
https://github.com/microsoft/project-rome Project Rome Obsolete source code (partial; jar src not found and android lib is old)
https://www.youtube.com/watch?v=Ewp9SznBbg4 MS Build 2017. Project Rome
https://developer.microsoft.com/en-us/windows/project-rome Project Rome for Developers (obsolete... has risk to be deleted)
https://github.com/johnthiriet/MediaExperience  Some ProjectRome experimentation (Xamarin Forms)
https://github.com/Code-ScottLe/Link-10 Link-10 Framework built that aim to help with cross-app communication between UWP apps and even Win32 app

**Comment by ShortDevelopment** [comment]
Hey, thanks for your interest!
   
I’m not really sure what you would want to read in such a wiki.    
This projects currently only contains a nice GUI wrapper around the [project rome sdk for (java) android]( https://github.com/microsoft/project-rome/tree/mvn-repo/com/microsoft/connecteddevices/connecteddevices-sdk) based on [this old ms sample]( https://github.com/microsoft/project-rome/tree/master/Android/samples/nearsharestandalone).
I modified the java bytecode a bit, as a method called from jni was missing (See #1).   

As windows devices have this build-in, there’s only this android app, that can currently only send files and urls to windows devices.   
   
As I want to provide some “receive” capability for android, I’m in the process of implementing the protocol myself ([See docs]( https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-cdp/)).

**Comment by mediaexplorer74** [comment]
> Hey, thanks for your interest!
Yea, it's realy wonderful world of IoT that you drive. :)
> I’m not really sure what you would want to read in such a wiki. This projects currently only contains a nice GUI wrapper around the [project rome sdk for (java) android](https://github.com/microsoft/project-rome/tree/mvn-repo/com/microsoft/connecteddevices/connecteddevices-sdk) based on [this old ms sample](https://github.com/microsoft/project-rome/tree/master/Android/samples/nearsharestandalone). I modified the java bytecode a bit, as a method called from jni was missing (See #1).
Thank you for rich comments. You are cleve and great developer :) I 'll try to research your links
> As windows devices have this build-in, there’s only this android app, that can currently only send files and urls to windows devices.
Ohh... I see. It's interesting
> As I want to provide some “receive” capability for android, I’m in the process of implementing the protocol myself ([See docs](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-cdp/)).
Ohhh....  Its veery haard to my mind ) I m very bad system develepor . Sorry, I m too old (

**Comment by ShortDevelopment** [comment]
Thanks!
I’ll keep working (as much as I’ll have time).

Once I got some "receiving" working, I'll probably update the readme!
