### ISSUE TITLE
App crash on language change attempt

### ISSUE THREAD

**Issue by ShortDevelopment** [ShortDevelopment/Nearby-Sharing-Windows#98]
Check should use the android build numbers
https://github.com/ShortDevelopment/Nearby-Sharing-Windows/blob/f267bca49d7fac7f198644cc4176cd8916e2377e/Nearby%20Sharing%20Windows/Settings/SettingsActivity.cs#L119

**Comment by HaoTian22** [comment]
By the way, I think this page will also crash (back to the "welcome" page) in Android 13?

**Comment by ShortDevelopment** [comment]
Sure? It seemed to work in my emulator with Android 13...

**Comment by HaoTian22** [comment]
Need I provide more information?
(but I don't know how to export the log, need some instructions)

**Comment by HaoTian22** [comment]
Maybe cause by some OEM modification?
I'm not sure

**Comment by HaoTian22** [comment]
Okay, it seems that it is MIUI's fault.
This option will link to a system setting page, which is modified and deleted on MIUI ROM.
It works well when I flash my system to PixelExperience

**Comment by HaoTian22** [comment]
hmmm, still not solve this problem yet (1.5.1 beta)

**Comment by ShortDevelopment** [comment]
@HaoTian22
I can't see the crash in the Google Play Console (yet) and I'm sadly over my sentry quota due to an old project.

Could you maybe try to extract some StackTrace or error message via `logcat`?

**Comment by HaoTian22** [comment]
sorry, but I don't really know how to extract the logs.
Can I just send you the result of `adb logcat -v time > logcat.log` to your discord? (I'm worried that there is something privacy in the log)

**Comment by ShortDevelopment** [comment]
@HaoTian22 Sure, just send me a DM on Discord or Email
